#! /usr/bin/bash
num_of_lines=$(awk 'END{print NR}' $2)
fields_types=($(awk -F: '{print $2}' $2)) #$2 carries the meta file path, so awk operates on it
fields_names=($(awk -F: '{print $1}' $2))

function valid_type () {
    #{fields_types[$i-1]} -> $1
    #value -> $3
    #path -> $2
    temp=$3
    if [[ $1 == "Integer" ]] ; then
        while [[ ! $temp =~ ^[0-9]+$ ]]; do
            read -p "Please enter an integer: " temp
        done
        echo -n $temp: >> $2 #./iti1/table_1 -> $3 (path of the table)
    else
        while [[ -z "$temp" ]];do
            read -p "Value cannot be empty, please enter a new value: " temp
        done
        echo -n $temp: >> $2
    fi
}

for ((i = 1; i <= num_of_lines; i++)); do
    read -p "Enter value for ${fields_names[$i-1]}: " value
    if [[ $i == 1 ]]; then
        while true; do
            check=$(awk -F: -v value="$value" '{
                if ($1 == value)
                { result=0
                    exit
                }} END { print result }' $1) #$1 is path of table
            if [[ "$check" == '0' || -z $value ]]; then
                read -p "Enter a unique primary key: " value
            else 
                break
            fi
        done
        valid_type ${fields_types[$i-1]} $1 "$value"
    else
        valid_type ${fields_types[$i-1]} $1 "$value"
    fi
    
done

echo -ne "\n" >> $1
source table_menue