#! /usr/bin/bash
source regex

PS3="Choose an option from the menu >>"
select option in "Create DB" "List DB" "Drop DB" "Connect to DB" "Press 5 or anything else to exit"
do
    case $REPLY in
        1) #Create DB
            read -p " Please Enter DB Name : " name
            if [[ "$(regex_table "$name")" == "1" ]]; then
                if [[ -e $name ]]; then
                    echo "A database with this name already exists."
                else 
                    mkdir $name
                fi
            else
                echo "Please enter a valid name. Database names should only start with a letter, can only contain alphanumeric chars or _, length should be between 3 and 64 chars."
            fi
        ;;
        2) #List DB
        ls -F | grep /
        ;;
        3) #Drop DB
        echo "Please choose which database to drop:"
        select option in $(ls -F | grep /)
        do
            if [ -n "$option" ]; then
                read -p "You selected: $option. Are you sure you want to delete the database? y/n" answer
                if [[ "$answer" == "y" ]]; then
                    rm -r "$option"
                    echo "Database deleted successfully."
                    break  # Exit the loop after a valid selection
                elif [[ "$answer" == "n" ]]; then
                    echo "No database deleted."
                    break
                else 
                echo "Invalid selection. Please try again."
                fi
            else
                echo "Invalid selection. Please try again."
            fi
        done
        ;;
        4) #Connect to DB
        echo "Please choose which database to connect to."
        select option in $(ls -F | grep /)
        do 
            if [ -n "$option" ]; then
                cd $option 
                source table_menue $option
            else
                echo "Invalid selection, you are back to main menu."
                break
            fi
        done
        ;;
        5) #Else
            echo "Press 5 or anything else to exit."
            exit
        ;;
        *)
        exit 
    esac
done