#! /usr/bin/bash
source regex

PS3="Choose an option from the menu >>"
select option in "Create DB" "List DB" "Drop DB" "Connect to DB" "Press 5 or anything else to exit"
do
    case $REPLY in
        1) #Create DB
            read -p " Please Enter DB Name : " name
            while [[ "$(regex_db "$name")" == "0" ]]; do
                read -p "Please enter a valid name. Database names should only start with a letter, can only contain alphanumeric chars or _, length should be between 2 and 64 chars." name
            done
            if [[ -e $name ]]; then
                    echo "A database with this name already exists."
                    source main_menu
                else 
                    echo "Database $name created"
                    mkdir $name
                    source main_menu
            fi
        ;;
        2) #List DB
        ls -F | grep /
        source main_menu
        ;;
        3) #Drop DB
        echo "Please choose which database to drop:"
        select option in $(ls -F | grep /)
        do
            if [ -n "$option" ]; then
                read -p "You selected: $option. Are you sure you want to delete the database? y/n" answer
                if [[ "$answer" == "y" ]]; then
                    rm -r "$option"
                    echo "Database deleted successfully."
                    source main_menu
                    break  # Exit the loop after a valid selection
                elif [[ "$answer" == "n" ]]; then
                    echo "No database deleted."
                    source main_menu
                    break
                else 
                echo "Invalid selection."
                source main_menu
                fi
            else
                echo "Invalid selection."
                source main_menu
            fi
        done
        ;;
        4) #Connect to DB
        echo "Please choose which database to connect to."
        select option in $(ls -F | grep /)
        do 
            if [ -n "$option" ]; then
                echo $PWD
                cd $option 
                source table_menue $option
            else
                echo "Invalid selection, you are back to main menu."
                source main_menu
                break
            fi
        done
        ;;
        5) #Else
            echo "Press 5 or anything else to exit."
            exit
        ;;
        *)
        exit 
    esac
done