#! /usr/bin/bash

echo $PWD
PS3="Choose an Option >> "
select  variable2 in "Create Table" "Drop Table" "Insert into Table" "select from Table" "Delet from Table" "Update Table" "List Tables" 
do
    case $REPLY in
        1) # "Create Table"
            source create_table
        ;;
        2) # "Drop Table"
            read -p "Enter Table Name: " table_name
            if [[ "$(regex_table "$table_name")" == "1" ]]; then 
                    if [ -f $table_name ];then
                        rm -i $table_name .meta_$table_name
                    else 
                        echo "The table does not exist"
                    fi 
            else
                echo "Not a valid Name"
            fi
            echo $variable2
        ;; 
        3) # "Insert into Table" 
        echo $variable2
        echo "Please choose which table to insert into."
        select option in $(ls -F | grep -v /)
        do 
            if [ -n "$option" ]; then
                source insert_table $option .meta_$option
            else
                echo "Invalid selection."
                source table_menue
                break
            fi
        done
        
        ;;
        4) #Select from table
        echo $variable2
        echo $PWD
        echo "Please choose which table to select from."
        select option in $(ls -F | grep -v /)
        do 
            if [ -n "$option" ]; then
                source select_table $option .meta_$option
            else
                echo "Invalid selection."
                source table_menue
                break
            fi
        done
        ;;
        5) # Delete from a table 
            echo $variable2
            echo "Please choose which table to delete from."
            select option in $(ls -F | grep -v /)
            do 
                if [ -n "$option" ]; then
                    source delete_from_table $option .meta_$option
                else
                    echo "Invalid selection."
                    source table_menue
                    break
                fi
                PS3="Choose an Option >> "
            done
        ;;
        6) # update table 
            echo $variable2
            echo "Please choose which table to update."
            select option in $(ls -F | grep -v /)
            do 
                if [ -n "$option" ]; then
                    source update_table $option .meta_$option
                else
                    echo "Invalid selection."
                    source table_menue
                    break
                fi
            done
        ;;
        7) # "List Tables" 
            echo "Existing Tables are: "
            ls -F | grep -v /
        ;;
        *)
        echo "Invalid option, you are back to main menu."
        cd ..
        source main_menu
        break
    esac
done 