#! /usr/bin/bash

source regex
echo $PWD
PS3="Choose an Option >> "
select  variable2 in "Create Table" "Drop Table" "Insert into Table" "select from Table" "Delet from Table" "Update Table" "List Tables" 
do
    case $REPLY in
        1) # "Create Table"
            read -p "Enter Table Name: " table_name
            if [[ "$(regex_table "$table_name")" == "1" ]]; then 
                if [ -f $table_name ];then
                    echo "The table already exists"
                else 
                    read -p "Enter number of fields: " no_fields 
                    touch $table_name .meta_$table_name
                    if [[ $no_fields =~ ^[0-9]+$ ]];then
                        for ((i = 1; i <= no_fields; i++)); do
                            PS3="Field Type: "
                            read -p "Enter field $i: " field_name
                            select field_type in "String" "Integer"
                            do
                                case $REPLY in
                                1) 
                                    echo "$field_name:$field_type;" >> .meta_$table_name
                                    break ;;
                                2)
                                    echo "$field_name:$field_type;" >> .meta_$table_name
                                    break ;;
                                esac
                            done 
                        done
                        PS3="Choose an Option >> "
                    else
                        echo "Not a valid number of fields "
                    fi
                fi
            else
                echo "Not a Valid Table Name"
            fi 

        ;;
        2) # "Drop Table"
            read -p "Enter Table Name: " table_name
            if [[ "$(regex_table "$table_name")" == "1" ]]; then 
                    if [ -f $table_name ];then
                        rm -i $table_name .meta_$table_name
                    else 
                        echo "The table does not exist"
                    fi 
            else
                echo "Not a valid Name"
            fi
            echo $variable2
        ;; 
        3) # "Insert into Table" 
        echo $variable2
        ;;
        4)
        echo $variable2
        ;;
        5) 
        echo $variable2
        ;;
        6) 
        echo $variable2
        ;;
        7) # "List Tables" 
            echo "Existing Tables are: "
            ls -F | grep -v /
        ;;
        *)
        echo "Invalid option, you are back to database connection menu"
        cd ..
        echo "Please choose which database to connect to."
        count=0
        directories=$(ls -F | grep /)
        for directory in $directories; do
            ((count=count+1))
            echo "$count: $directory"
        done
        break
    esac
done 