#! /usr/bin/bash
fields_names=($(awk -F: '{print $1}' $2))
read -p "Enter the primary key for the row you want to update: " row_value
line_number=$(awk -F: -v row_value="$row_value" 'BEGIN{line_number=0}{
                if($1 == row_value)
                {
                    line_number = NR
                }
            }END {print line_number}' $1)
if [[ $line_number == 0 ]]; then
                echo "The id you entered does not exist!"
                source update_table
else
   select column_name in ${fields_names[@]:1}
            do
                if [[ $REPLY =~ ^[1-9]$ && $((REPLY+1)) -le ${#fields_names[@]} ]]; then
                    read -p "Enter new value: " new_value
                
                        awk -F: -v OFS=: -v col="$((REPLY+1))" -v line_number="$line_number" -v new_value="$new_value" '{
                            if(NR != line_number)
                            {
                                print $0 
                            }
                            else{
                                $col=new_value
                                print $0
                            }}' $1 > temp_file && mv temp_file $1
                else
                    break
                fi
            done
fi 
